version: '3.5'
services:
  # Clients Data Base (MySQL DB)
  clients-db:
    container_name: mysql8-db
    image: mysql:8.0.34
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clients
    ports:
      - "3306:3306"
    restart: on-failure

  # Accounts Data Base (Postgres DB)
  accounts-db:
    container_name: postgres16-db
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accounts
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: on-failure
